// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Toggle = /* module */[];

var Collapse = /* module */[];

exports.Toggle = Toggle;
exports.Collapse = Collapse;
/* No side effect */
