// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function str(prim) {
  return prim;
}

var url = "https://tipitaka.org/romn/tipitaka_toc.xml";

function tree(text) {
  return /* :: */[
          /* record */[
            /* text */"Tipitaka",
            /* src */"opalapa.xml"
          ],
          /* [] */0
        ];
}

var Decode = /* module */[/* tree */tree];

function fetchTopics(param) {
  return fetch(url).then((function (prim) {
                    return prim.text();
                  })).then((function (text) {
                  return Promise.resolve(/* :: */[
                              /* record */[
                                /* text */"Tipitaka",
                                /* src */"opalapa.xml"
                              ],
                              /* [] */0
                            ]);
                })).catch((function (_err) {
                return Promise.resolve(undefined);
              }));
}

var component = ReasonReact.reducerComponent("Tipitaka");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              if (typeof match === "number") {
                switch (match) {
                  case 0 : 
                      return React.createElement("div", undefined, "Click to start load Topics", React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* LoadTopics */0);
                                        })
                                    }, "Load Topics"));
                  case 1 : 
                      return React.createElement("div", undefined, "Loading...");
                  case 2 : 
                      return React.createElement("div", undefined, "Something went wrong!");
                  
                }
              } else {
                return React.createElement("div", undefined, React.createElement("h2", undefined, "Topics"), React.createElement("ul", undefined, $$Array.of_list(List.map((function (topic) {
                                          return React.createElement("li", {
                                                      key: topic[/* text */0]
                                                    }, topic[/* text */0]);
                                        }), match[0]))));
              }
            }),
          /* initialState */(function (param) {
              return /* NotAsked */0;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* Failure */2]);
                } else {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            /* Loading */1,
                            (function (self) {
                                fetchTopics(/* () */0).then((function (result) {
                                        if (result !== undefined) {
                                          return Promise.resolve(Curry._1(self[/* send */3], /* LoadedTopics */[result]));
                                        } else {
                                          return Promise.resolve(Curry._1(self[/* send */3], /* LoadTopicsFailed */1));
                                        }
                                      }));
                                return /* () */0;
                              })
                          ]);
                }
              } else {
                return /* Update */Block.__(0, [/* Success */[action[0]]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.str = str;
exports.url = url;
exports.Decode = Decode;
exports.fetchTopics = fetchTopics;
exports.component = component;
exports.make = make;
/* component Not a pure module */
