// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var CardJs = require("react-bootstrap/Card.js");
var AccordionJs = require("react-bootstrap/Accordion.js");

function App(Props) {
  var cardHeader = function (children) {
    return React.createElement(CardJs.Header, {
                children: children
              });
  };
  return React.createElement(AccordionJs, {
              children: null
            }, React.createElement(CardJs, {
                  children: null
                }, React.createElement(AccordionJs.Toggle, {
                      as_: cardHeader,
                      eventKey: "0",
                      children: "Click me!"
                    }), React.createElement(AccordionJs.Collapse, {
                      eventKey: "0",
                      children: React.createElement(CardJs.Body, {
                            children: "Hello! I'm the body"
                          })
                    })), React.createElement(CardJs, {
                  children: null
                }, React.createElement(AccordionJs.Toggle, {
                      as_: cardHeader,
                      eventKey: "1",
                      children: "Click me! 002"
                    }), React.createElement(AccordionJs.Collapse, {
                      eventKey: "1",
                      children: React.createElement(CardJs.Body, {
                            children: "Hello! I'm the body 002"
                          })
                    })), React.createElement(CardJs, {
                  children: null
                }, React.createElement(AccordionJs.Toggle, {
                      as_: cardHeader,
                      eventKey: "2",
                      children: "Click me! 003"
                    }), React.createElement(AccordionJs.Collapse, {
                      eventKey: "2",
                      children: React.createElement(CardJs.Body, {
                            children: "Hello! I'm the body 003"
                          })
                    })));
}

var make = App;

exports.make = make;
/* react Not a pure module */
