// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Header = /* module */[];

var Body = /* module */[];

exports.Header = Header;
exports.Body = Body;
/* No side effect */
